### ISSUE TITLE
If you zoom out on the 'Coordinates' map, I would expect to be able to select a new 'position' for my location.

### ISSUE THREAD

**Issue by bryantebeek** [LumenoDev/bugs#14]
Instead of letting me select a new location, it seems like I can only add new pointers as long as they are on a 0.01 LAT or 0.01 LON degree grid. See my screenshot for an example. It only works if you zoom out to a level where clicking makes a 0.01 difference.

Btw this is not my actual location 👍

![CleanShot 2022-07-03 at 12 43 02@2x](https://user-images.githubusercontent.com/2136273/177036069-6e952ac0-25e7-40e7-85d1-82c109915bf6.png)

**Comment by mattkingshott** [comment]
I reckon this is due to Lumeno not storing anything past 2 decimal places (for privacy reasons). It won't let you select an area that is also within that same area e.g. km squared. It shouldn't be placing more than one pin though. I'll fix that. Maybe I should add a notice about needing to be a certain distance away from an existing pin?

**Comment by bryantebeek** [comment]
@mattkingshott yeah that might be a good option (the notice)! And maybe make the initial zoom a bit further out, so it is actually possible to click and move the point (at least 0.01 deg in both directions). About 2 or 3 times pressing the zoom out 'minus' would make more sense I guess? 👍

**Comment by mattkingshott** [comment]
Cool. I'll do that
